jwt:
  time: 1000
  secret: hello-world

posco:
  name: 3기
  count: 20

test:
  datasource:
    url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
